WEAPON_STATS = {
    "short sword": {"base_damage": 6, "hit_modifier": 4, "type": "Short Blades"},
    "dagger": {"base_damage": 4, "hit_modifier": 6, "type": "Short Blades"},
    "quick blade": {"base_damage": 5, "hit_modifier": 6, "type": "Short Blades"},
    "rapier": {"base_damage": 8, "hit_modifier": 4, "type": "Short Blades"},
    "falchion": {"base_damage": 7, "hit_modifier": 2, "type": "Long Blades"},
    "long sword": {"base_damage": 9, "hit_modifier": 1, "type": "Long Blades"},
    "scimitar": {"base_damage": 11, "hit_modifier": 0, "type": "Long Blades"},
    "demon blade": {"base_damage": 12, "hit_modifier": -1, "type": "Long Blades"},
    "double sword": {"base_damage": 14, "hit_modifier": -1, "type": "Long Blades"},
    "eudemon blade": {"base_damage": 13, "hit_modifier": -2, "type": "Long Blades"},
    "great sword": {"base_damage": 15, "hit_modifier": -3, "type": "Long Blades"},
    "triple sword": {"base_damage": 17, "hit_modifier": -4, "type": "Long Blades"},
    "hand axe": {"base_damage": 7, "hit_modifier": 3, "type": "Axes"},
    "war axe": {"base_damage": 11, "hit_modifier": 0, "type": "Axes"},
    "broad axe": {"base_damage": 13, "hit_modifier": -2, "type": "Axes"},
    "battleaxe": {"base_damage": 15, "hit_modifier": -4, "type": "Axes"},
    "executioner's axe": {"base_damage": 18, "hit_modifier": -6, "type": "Axes"},
    "whip": {"base_damage": 6, "hit_modifier": 2, "type": "Axes"},
    "club": {"base_damage": 5, "hit_modifier": 3, "type": "Axes"},
    "mace": {"base_damage": 8, "hit_modifier": 3, "type": "Axes"},
    "flail": {"base_damage": 10, "hit_modifier": 0, "type": "Axes"},
    "Morningstar": {"base_damage": 13, "hit_modifier": -2, "type": "Axes"},
    "demon whip": {"base_damage": 11, "hit_modifier": 1, "type": "Axes"},
    "sacred scourge": {"base_damage": 12, "hit_modifier": 0, "type": "Axes"},
    "dire flail": {"base_damage": 13, "hit_modifier": -3, "type": "Axes"},
    "eveningstar": {"base_damage": 15, "hit_modifier": -1, "type": "Axes"},
    "eveningstar": {"base_damage": 15, "hit_modifier": -1, "type": "Axes"},
    "great mace": {"base_damage": 17, "hit_modifier": -4, "type": "Axes"},
    "giant club": {"base_damage": 20, "hit_modifier": -6, "type": "Axes"},
    "giant spiked club": {"base_damage": 22, "hit_modifier": -7, "type": "Axes"},
    "spear": {"base_damage": 6, "hit_modifier": 4, "type": "Axes"},
    "trident": {"base_damage": 9, "hit_modifier": 1, "type": "Polearms"},
    "halberd": {"base_damage": 13, "hit_modifier": -3, "type": "Polearms"},
    "scythe": {"base_damage": 14, "hit_modifier": -4, "type": "Polearms"},
    "demon trident": {"base_damage": 12, "hit_modifier": +1, "type": "Polearms"},
    "trishula": {"base_damage": 13, "hit_modifier": 0, "type": "Polearms"},
    "glaive": {"base_damage": 15, "hit_modifier": -3, "type": "Polearms"},
    "bardiche": {"base_damage": 18, "hit_modifier": -6, "type": "Polearms"},
    "staff": {"base_damage": 5, "hit_modifier": 5, "type": "Staves"},
    "quarterstaff": {"base_damage": 10, "hit_modifier": 3, "type": "Staves"},
    "lajatang": {"base_damage": 16, "hit_modifier": -3, "type": "Staves"},
    "hand crossbow": {"base_damage": 12, "hit_modifier": 5, "type": "Crossbows"},
    "arbalest": {"base_damage": 18, "hit_modifier": 2, "type": "Crossbows"},
    "triple crossbow": {"base_damage": 22, "hit_modifier": 0, "type": "Crossbows"},
    "hunting sling": {"base_damage": 5, "hit_modifier": 2, "type": "Slings"},
    "fustibalus": {"base_damage": 8, "hit_modifier": -1, "type": "Slings"},
    "blowgun": {"base_damage": 0, "hit_modifier": 2, "type": "Throwing"},
    "longbow": {"base_damage": 15, "hit_modifier": 0, "type": "Bows"},
    "shortbow": {"base_damage": 9, "hit_modifier": 2, "type": "Bows"},
    "sdaf": {"base_damage": 9, "hit_modifier": 2, "type": "Bows"},
}
